# Generated by Django 4.2.4 on 2023-08-21 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('upi', 'UPI'), ('debit card', 'Debit Card'), ('credit card', 'Credit Card'), ('cheque', 'Cheque'), ('others', 'Others')], max_length=50)),
                ('payment_status', models.CharField(choices=[('due', 'Due'), ('paid', 'Paid')], max_length=20)),
                ('total_amount', models.FloatField()),
                ('due', models.FloatField()),
                ('advance', models.FloatField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=500)),
                ('pincode', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(choices=[('cbc', 'CBC'), ('liver function', 'Liver Function'), ('cholesterol profile', 'Cholesterol Profile'), ('urinalysis', 'Urinalysis')], max_length=120)),
                ('price', models.FloatField()),
                ('tests_status', models.CharField(choices=[('pending', 'Pending'), ('competed', 'Competed')], default='pending', max_length=50)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab.bills')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab.lab')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UrinalysisTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('color', models.CharField(max_length=20)),
                ('appearance', models.CharField(max_length=50)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab.tests')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiverFunctionTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ast', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_bilirubin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('direct_bilirubin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab.tests')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=13)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Others', 'OTHERS')], max_length=20)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lab.lab')),
                ('lab_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab.labuser')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CholesterolProfileTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_cholesterol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hdl_cholesterol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ldl_cholesterol', models.DecimalField(decimal_places=2, max_digits=5)),
                ('triglycerides', models.DecimalField(decimal_places=2, max_digits=5)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab.tests')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CBCTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hemoglobin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wbc_count', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rbc_count', models.DecimalField(decimal_places=2, max_digits=7)),
                ('platelet_count', models.PositiveIntegerField()),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab.tests')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='bills',
            name='lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab.lab'),
        ),
        migrations.AddField(
            model_name='bills',
            name='lab_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab.labuser'),
        ),
        migrations.AddField(
            model_name='bills',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
